#!/bin/bash

for summarypath in `ls $1/summary*` #`find $1 -name "summary*"` or just ls $1/*summary*
do
	mean=`${ROS_SCRIPTS}/collect < $summarypath | ${ROS_SCRIPTS}/mean.py`

	summaryname=`basename "$summarypath"`

	echo $mean $summaryname
done
