#!/bin/bash

# paths
PROJECT_PATH=/Users/user/storm/reteonstorm
SCRIPTS_PATH=${PROJECT_PATH}/scripts

# input-size dependent arrays
SIZE=( 1 )
TIME=( 5 )
i=1
for s in `seq 5 5`;do
	SIZE[$i]=`expr $s \* 10000`
	TIME[$i]=`echo "($s+0)*20" | bc`
	(( i++ ))
done

# input-size independent arrays
NODES=( 2 )
SHARE=( false )
FPAR=( 2 )

for nodes in ${NODES[@]};do
	for share in ${SHARE[@]};do
		for fpar in ${FPAR[@]};do
			#if [ $share == true ] && [ $fpar -eq 2 ]; then continue fi
			for (( i=0; i<${#SIZE[@]}; i++ ));do

				date
				echo "i=$i" "size[i]=${SIZE[$i]}" "time[i]=${TIME[$i]}"

				# this iteration is an experiment
				# each experiment runs reteonstorm 5 times and produces a single summary file
				# each "different" experiment should be given a different id (-eid)
				# giving the same -eid would overwrite the previous logs/summary files

				${SCRIPTS_PATH}/experiment \
					-n $nodes \
					-ns $share \
					-fp $fpar \
					-i ${SIZE[$i]} \
					-ttl ${TIME[$i]} \
					-eid "nodes${nodes}_share${share}_fpar${fpar}_size${SIZE[$i]}"
			done
		done
	done
done
echo measure done
