#!/bin/bash

# $1 = log file to summarise (ie. to print last Ack time and any Exceptions)
# $2 = if this is equal to -o, summary includes <result> and $3 is necessary
# $3 = expected lines between <result> and </result> (non-inclusive)

last_ack_in_millis=`cat $1 | awk '/Acking/{print $1}' | tail -1`
last_ack_in_seconds=`echo "scale=3;${last_ack_in_millis}/1000" | bc`
echo last_ack@${last_ack_in_seconds}

if [[ `grep -m 1 -i "fail" < $1` ]]; then
	echo FAILURES EXIST
fi

grep Exception < $1

if [ "$2" = "-o" ] ; then 
  cat $1 | grep -A `expr $3 + 1` \<result 
fi

echo
